version: '3.8'

services:
  creative-lens:
    build: .
    container_name: creative-lens-mcp
    restart: unless-stopped
    environment:
      - LOG_LEVEL=${LOG_LEVEL:-info}
      - PERSISTENCE_TYPE=${PERSISTENCE_TYPE:-file}
      - MAX_SESSIONS=${MAX_SESSIONS:-100}
      - SESSION_TIMEOUT=${SESSION_TIMEOUT:-3600000}
    volumes:
      - ./data:/app/data
      - ./logs:/app/logs
    ports:
      - "3000:3000"  # Only if using TCP transport
    healthcheck:
      test: ["CMD", "node", "-e", "console.log('OK')"]
      interval: 30s
      timeout: 3s
      retries: 3
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  # Optional: Redis for distributed state
  redis:
    image: redis:7-alpine
    container_name: creative-lens-redis
    restart: unless-stopped
    volumes:
      - redis-data:/data
    command: redis-server --appendonly yes
    profiles:
      - distributed

volumes:
  redis-data: